version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  data:
